$ErrorActionPreference = 'Stop'

Write-Host ''
Write-Host 'HiTechClaw AI developer workflow summary'
Write-Host '====================================='
Write-Host ''
Write-Host 'Setup:'
Write-Host '  1. Copy-Item .env.development.example .env.local'
Write-Host '  2. Copy-Item .env.test.example .env.test.local'
Write-Host '  3. npm install'
Write-Host '  4. npm run dev:up'
Write-Host '  5. npm run test:setup'
Write-Host '  6. npm run hooks:install   # optional but recommended'
Write-Host ''
Write-Host 'Daily use:'
Write-Host '  - npm run dev              # run app locally'
Write-Host '  - npm run check:local      # lint + smoke path'
Write-Host '  - npm run check:pre-push   # stronger push gate'
Write-Host ''
Write-Host 'Cleanup:'
Write-Host '  - npm run dev:clean'
Write-Host '  - npm run test:clean'
Write-Host '  - npm run clean:all'
Write-Host ''
Write-Host 'References:'
Write-Host '  - docs/development.md'
Write-Host '  - CONTRIBUTING.md'
Write-Host '  - INSTALL.md'
Write-Host ''
