export type AppRoute = {
  path: string;
  label: string;
};

export const CORE_PAGES: AppRoute[] = [
  { path: "/", label: "Dashboard" },
  { path: "/activity", label: "Activity" },
  { path: "/admin", label: "Admin" },
  { path: "/agents", label: "Agents" },
  { path: "/security", label: "ThreatGuard" },
  { path: "/costs", label: "Costs" },
  { path: "/workflows", label: "Workflows" },
  { path: "/infrastructure", label: "Infrastructure" },
  { path: "/analytics", label: "Anomaly Detection" },
  { path: "/benchmarks", label: "Benchmarks" },
  { path: "/compliance", label: "Compliance" },
  { path: "/tools/approvals", label: "Approvals" },
  { path: "/tools/calendar", label: "Calendar" },
  { path: "/tools/command", label: "Commands" },
  { path: "/tools/docs", label: "Docs" },
  { path: "/tools/tasks", label: "Tasks" },
  { path: "/tools/crons", label: "Cron Jobs" },
  { path: "/tools/intake", label: "Intake" },
  { path: "/tools/mcp", label: "MCP Servers" },
  { path: "/tools/mcp-gateway", label: "MCP Gateway" },
  { path: "/settings/notifications", label: "Notification Settings" },
  { path: "/help/glossary", label: "Glossary" },
];

export const EXTENDED_PAGES: AppRoute[] = [
  { path: "/", label: "Dashboard" },
  { path: "/activity", label: "Activity" },
  { path: "/agents", label: "Agents" },
  { path: "/analytics", label: "Anomaly Detection" },
  { path: "/infrastructure", label: "Infrastructure" },
  { path: "/traces", label: "Traces" },
  { path: "/victoryos", label: "VictoryOS" },
  { path: "/security", label: "ThreatGuard" },
  { path: "/tools/command", label: "Command" },
  { path: "/tools/approvals", label: "Approvals" },
  { path: "/tools/agents-live", label: "Live Agents" },
  { path: "/workflows", label: "Workflows" },
  { path: "/tools/crons", label: "Cron Jobs" },
  { path: "/tools/tasks", label: "Tasks" },
  { path: "/costs", label: "Costs" },
  { path: "/compliance", label: "Compliance" },
  { path: "/benchmarks", label: "Benchmarks" },
  { path: "/admin", label: "Admin Panel" },
  { path: "/settings", label: "Settings" },
  { path: "/settings/sessions", label: "Sessions" },
  { path: "/settings/notifications", label: "Notification Settings" },
  { path: "/tools/docs", label: "Docs" },
  { path: "/tools/mcp", label: "MCP Servers" },
  { path: "/tools/mcp-gateway", label: "MCP Gateway" },
  { path: "/tools/intake", label: "Client Intake" },
  { path: "/tools/calendar", label: "Calendar" },
  { path: "/help/glossary", label: "Glossary" },
  { path: "/client", label: "Client Portal" },
  { path: "/client/agents", label: "Client Agents" },
  { path: "/client/costs", label: "Client Costs" },
  { path: "/client/api-keys", label: "Client API Keys" },
  { path: "/login", label: "Login" },
];
